version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-identity
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_DATABASE: file-upload
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./mysql-file-upload-data:/var/lib/mysql
    networks:
      - file-upload-network

  redis:
    container_name: redis-identity
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_AOF_ENABLED=yes
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6381:6379"
    volumes:
      - ./redis/data:/bitnami/redis/data
    networks:
      - file-upload-network

  scan:
    hostname: avscan
    container_name: avscan
    # build: ./scan/.
    image: mailu/clamav:latest
    ports:
      - "3310:3310"
    restart: always

volumes:
  mysql-file-upload-data:
    driver: local

networks:
  file-upload-network:
    driver: bridge